[phases.setup]
nixPkgs = ["chromium", "glib", "nss", "atk", "cups", "libdrm", "xorg.libxkbcommon", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXfixes", "xorg.libXrandr", "mesa", "alsa-lib"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'Build done'"]

[start]
cmd = "node bot.js"